### PR TITLE
Add German translations

### PR DESCRIPTION
**Pull request by Scotsguy**
Not quite so sure on some of these, technical writing in German isn't my strong suit
Reviews appreciated

### CODE REVIEW

**Comment by InvalidName662** [comment]
Maybe Im just blind but didnt you write the German Translation in the file for America?

**Comment by Scotsguy** [comment]
You are correct. Fixed.

**Comment by InvalidName662** [comment]
Also I would change 'Unvertraut' to something like 'Mißtrauen' since Unvertraut does not mean 'Untrusted' but 'Unfamiliar'.

**Comment by TheOneTrueZandra** [comment]
@Scotsguy We added localization for the rest of the UI elements, if you'd like to update this PR with new localizations.

**Comment by TheOneTrueZandra** [comment]
Didn't mean to close this, sorry

**Pull request closed without merging**
